const artistData = [
	["jamaal", 1, 0, 0, 0, 0],
	["mo", 1, 0, 0, 0, 0],
	["sung", 0, 1, 0, 0, 0],
	["luke", 0, 1, 0, 0, 0],
	["paulymark", 0, 0, 1, 0, 0],
	["stevie", 0, 0, 1, 0, 0],
	["corey", 0, 0, 0, 1, 0],
	["vin", 0, 0, 0, 1, 0],
	["maxwell", 1, 1, 0, 0, 1],
	["lance", 0, 1, 1, 0, 1],
	["dylan", 0, 0, 1, 1, 1],
	["zak", 1, 0, 0, 1, 1],
	["lesean", 0, 1, 0, 1, 1],
	["sebastian", 1, 0, 1, 0, 1],
	["pierre", 0, 1, 0, 1, 1],
	["jalen", 1, 0, 1, 0, 1],
	["diego", 2, 1, 0, 0, 2],
	["lilhop", 0, 2, 1, 0, 2],
	["sky", 0, 0, 2, 1, 2],
	["anthem", 1, 0, 0, 2, 2],
	["omar", 1, 1, 1, 0, 2],
	["oscar", 0, 1, 1, 1, 2],
	["harrison", 1, 0, 1, 1, 2],
	["antonio", 1, 1, 0, 1, 2],
	["kyle", 0, 0, 3, 0, 3],
	["punchy", 0, 3, 0, 0, 3],
	["oldfrank", 0, 0, 0, 3, 3],
	["thetwins", 3, 0, 0, 0, 3]]

	const starData = [
		["showstopper", 1, 1, 0, 0, "artist", false, false, false],
		["beatbox", 1, 1, 0, 0, "artist", false, false, false],
		["acapella", 1, 0, 1, 0, "artist", false, false, false],
		["puppylove", 1, 0, 1, 0, "artist", false, false, false],
		["viralvideo", 1, 0, 0, 1, "artist", false, false, false],
		["privatetutor", 1, 0, 0, 1, "artist", false, false, false],
		["bootyshake", 0, 1, 0, 1, "artist", false, false, false],
		["personaltrainer", 0, 1, 0, 1, "artist", false, false, false],
		["intergalacticstomp", 0, 1, 1, 0, "artist", false, false, false],
		["hotkicks", 0, 1, 1, 0, "artist", false, false, false],
		["parachutepants", 0, 0, 1, 1, "artist", false, false, false],
		["frostedtips", 0, 0, 1, 1, "artist", false, false, false],
		["4partharmony", 2, 0, 0, 0, "artist", false, false, false],
		["backingvocals", 2, 0, 0, 0, "artist", false, false, false],
		["accoustictrack", 2, 0, 0, 0, "artist", false, false, false],
		["nonstopchoreography", 0, 2, 0, 0, "artist", false, false, false],
		["backupdancers", 0, 2, 0, 0, "artist", false, false, false],
		["exclusivecontract", 0, 2, 0, 0, "artist", false, false, false],
		["tabloidromance", 0, 0, 2, 0, "artist", false, false, false],
		["dreamdate", 0, 0, 2, 0, "artist", false, false, false],
		["stayingpure", 0, 0, 2, 0, "artist", false, false, false],
		["entourage", 0, 0, 0, 2, "artist", false, false, false],
		["faddiet", 0, 0, 0, 2, "artist", false, false, false],
		["rehab", 0, 0, 0, 2, "artist", false, false, false],
		["goingsolo", 0, 0, 0, 0, "artist-4", false, true, false],
		["badhabits", 0, 0, 0, 0, "artist", true, false, false],
		["rapidweightgain", 0, 0, 0, 0, "artist", true, false, false],
		["acne", 0, 0, 0, 0, "artist", true, false, false],
		["malepatternbaldness", 0, 0, 0, 0, "artist", true, false, false],
		["highnote", 3, 0, 0, 0, "artist-temp", false, true, true],
		["grouplove", 0, 3, 0, 0, "artist-temp", false, true, true],
		["asinglerose", 0, 0, 3, 0, "artist-temp", false, true, true],
		["sickride", 0, 0, 0, 3, "artist-temp", false, true, true],
		["sixpack", 0, 0, 0, 0, "artist-temp", false, true, true],
		["babyface", 0, 0, 0, 0, "artist-temp", false, true, true],
		["lawyerdad", 0, 0, 0, 0, "star-action", false, true, true],
		["stageparents", 0, 0, 0, 0, "star-action", false, true, true],
		["skydivinginjury", 0, 0, 0, 0, "gig-action", false, true, true],
		["strepthroat", 0, 0, 0, 0, "gig-action", false, true, true],
		["newrepresentation", 0, 0, 0, 0, "artist-0", false, true, false],
		["surprisecameo", 0, 0, 0, 0, "artist-temp", false, true, false],
		["stolenpracticetapes", 0, 0, 0, 0, "star-played", false, true, false],
		["secretlove", 0, 0, 0, 0, "star-played", false, true, false],
		["newmaterial", 0, 0, 0, 0, "hand", false, true, false],
		["sketchyaccountant", 0, 0, 0, 0, "hand", false, true, false],
		["paparazzimeltdown", 0, 0, 0, 0, "star-played", true, true, false],
		["toxicmasculinity", 0, 0, 0, 0, "star-played", true, true, false],
		["lousypublicist", 0, 0, 0, 0, "band", false, true, false]]

		const gigData = [
			["malltour", 0, 3, 3, 0, 20, false],
			["benefitconcert", 0, 3, 3, 0, 20, false],
			["radiopromos", 3, 0, 3, 0, 20, false],
			["teenagefanclub", 0, 0, 3, 3, 20, false],
			["halftimeshow", 3, 3, 0, 0, 20, false],
			["hitsingle", 3, 0, 0, 3, 20, false],
			["pressconference", 3, 0, 0, 0, 40, true],
			["productendorsement", 0, 0, 0, 3, 40, true],
			["daytimetalkshow", 0, 3, 0, 0, 40, true],
			["magazinecover", 0, 0, 3, 0, 40, true],
			["newalbum", 4, 0, 0, 0, 40, false, "1x4"],
			["musicvideo", 0, 4, 0, 0, 40, false, "1x4"],
			["autographsigning", 0, 0, 4, 0, 40, false, "1x4"],
			["realitytvshow", 0, 0, 0, 4, 40, false, "1x4"],
			["platinumalbum", 4, 0, 0, 4, 60, false],
			["goingtropical", 0, 0, 4, 4, 60, false],
			["holidayspecial", 4, 4, 0, 0, 60, false],
			["awardshow", 0, 4, 0, 4, 60, false],
			["spacecamp", 0, 0, 0, 0, 60, false, "t12"],
			["moviedeal", 0, 0, 0, 0, 60, false, "3x3"],
			["charityauction", 0, 0, 0, 0, 80, false, "2x5"],
			["privateevent", 0, 0, 0, 0, 80, false, "1x6"],
			["topofthecharts", 0, 0, 0, 0, 80, false, "m"],
			["worldtour", 3, 3, 3, 3, 100, false]]
